<?php
/**
 * AppAclGetRight
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Kintone
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * REST API SPEC
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20250423000000
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Kintone\Model;

use \ArrayAccess;
use \Kintone\ObjectSerializer;

/**
 * AppAclGetRight Class Doc Comment
 *
 * @category Class
 * @package  Kintone
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AppAclGetRight implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AppAclGetRight';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'app_editable' => 'bool',
        'entity' => '\Kintone\Model\AppAclGetRightEntity',
        'include_subs' => 'bool',
        'record_addable' => 'bool',
        'record_deletable' => 'bool',
        'record_editable' => 'bool',
        'record_exportable' => 'bool',
        'record_importable' => 'bool',
        'record_viewable' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'app_editable' => null,
        'entity' => null,
        'include_subs' => null,
        'record_addable' => null,
        'record_deletable' => null,
        'record_editable' => null,
        'record_exportable' => null,
        'record_importable' => null,
        'record_viewable' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'app_editable' => false,
        'entity' => false,
        'include_subs' => false,
        'record_addable' => false,
        'record_deletable' => false,
        'record_editable' => false,
        'record_exportable' => false,
        'record_importable' => false,
        'record_viewable' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'app_editable' => 'appEditable',
        'entity' => 'entity',
        'include_subs' => 'includeSubs',
        'record_addable' => 'recordAddable',
        'record_deletable' => 'recordDeletable',
        'record_editable' => 'recordEditable',
        'record_exportable' => 'recordExportable',
        'record_importable' => 'recordImportable',
        'record_viewable' => 'recordViewable'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'app_editable' => 'setAppEditable',
        'entity' => 'setEntity',
        'include_subs' => 'setIncludeSubs',
        'record_addable' => 'setRecordAddable',
        'record_deletable' => 'setRecordDeletable',
        'record_editable' => 'setRecordEditable',
        'record_exportable' => 'setRecordExportable',
        'record_importable' => 'setRecordImportable',
        'record_viewable' => 'setRecordViewable'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'app_editable' => 'getAppEditable',
        'entity' => 'getEntity',
        'include_subs' => 'getIncludeSubs',
        'record_addable' => 'getRecordAddable',
        'record_deletable' => 'getRecordDeletable',
        'record_editable' => 'getRecordEditable',
        'record_exportable' => 'getRecordExportable',
        'record_importable' => 'getRecordImportable',
        'record_viewable' => 'getRecordViewable'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('app_editable', $data ?? [], null);
        $this->setIfExists('entity', $data ?? [], null);
        $this->setIfExists('include_subs', $data ?? [], null);
        $this->setIfExists('record_addable', $data ?? [], null);
        $this->setIfExists('record_deletable', $data ?? [], null);
        $this->setIfExists('record_editable', $data ?? [], null);
        $this->setIfExists('record_exportable', $data ?? [], null);
        $this->setIfExists('record_importable', $data ?? [], null);
        $this->setIfExists('record_viewable', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets app_editable
     *
     * @return bool|null
     */
    public function getAppEditable()
    {
        return $this->container['app_editable'];
    }

    /**
     * Sets app_editable
     *
     * @param bool|null $app_editable The App management permission of the entity. Entities with this permission are able to access and edit the App's settings. - true: The App's settings are accessible. - false: The App's settings are not accessible.
     *
     * @return self
     */
    public function setAppEditable($app_editable)
    {
        if (is_null($app_editable)) {
            throw new \InvalidArgumentException('non-nullable app_editable cannot be null');
        }
        $this->container['app_editable'] = $app_editable;

        return $this;
    }

    /**
     * Gets entity
     *
     * @return \Kintone\Model\AppAclGetRightEntity|null
     */
    public function getEntity()
    {
        return $this->container['entity'];
    }

    /**
     * Sets entity
     *
     * @param \Kintone\Model\AppAclGetRightEntity|null $entity entity
     *
     * @return self
     */
    public function setEntity($entity)
    {
        if (is_null($entity)) {
            throw new \InvalidArgumentException('non-nullable entity cannot be null');
        }
        $this->container['entity'] = $entity;

        return $this;
    }

    /**
     * Gets include_subs
     *
     * @return bool|null
     */
    public function getIncludeSubs()
    {
        return $this->container['include_subs'];
    }

    /**
     * Sets include_subs
     *
     * @param bool|null $include_subs The permission inheritance settings of the department the permission is granted to. - true: Permissions are inherited. - false: Permissions are not inherited.
     *
     * @return self
     */
    public function setIncludeSubs($include_subs)
    {
        if (is_null($include_subs)) {
            throw new \InvalidArgumentException('non-nullable include_subs cannot be null');
        }
        $this->container['include_subs'] = $include_subs;

        return $this;
    }

    /**
     * Gets record_addable
     *
     * @return bool|null
     */
    public function getRecordAddable()
    {
        return $this->container['record_addable'];
    }

    /**
     * Sets record_addable
     *
     * @param bool|null $record_addable The record add permission of the entity - true: Records can be added. - false: Records cannot be added.
     *
     * @return self
     */
    public function setRecordAddable($record_addable)
    {
        if (is_null($record_addable)) {
            throw new \InvalidArgumentException('non-nullable record_addable cannot be null');
        }
        $this->container['record_addable'] = $record_addable;

        return $this;
    }

    /**
     * Gets record_deletable
     *
     * @return bool|null
     */
    public function getRecordDeletable()
    {
        return $this->container['record_deletable'];
    }

    /**
     * Sets record_deletable
     *
     * @param bool|null $record_deletable The record delete permission of the entity - true: Records are deletable. - false: Records are not deletable.
     *
     * @return self
     */
    public function setRecordDeletable($record_deletable)
    {
        if (is_null($record_deletable)) {
            throw new \InvalidArgumentException('non-nullable record_deletable cannot be null');
        }
        $this->container['record_deletable'] = $record_deletable;

        return $this;
    }

    /**
     * Gets record_editable
     *
     * @return bool|null
     */
    public function getRecordEditable()
    {
        return $this->container['record_editable'];
    }

    /**
     * Sets record_editable
     *
     * @param bool|null $record_editable The record edit permission of the entity - true: Records are editable. - false: Records are not editable.
     *
     * @return self
     */
    public function setRecordEditable($record_editable)
    {
        if (is_null($record_editable)) {
            throw new \InvalidArgumentException('non-nullable record_editable cannot be null');
        }
        $this->container['record_editable'] = $record_editable;

        return $this;
    }

    /**
     * Gets record_exportable
     *
     * @return bool|null
     */
    public function getRecordExportable()
    {
        return $this->container['record_exportable'];
    }

    /**
     * Sets record_exportable
     *
     * @param bool|null $record_exportable The record export permission of the entity - true: Records are exportable. - false: Records are not exportable.
     *
     * @return self
     */
    public function setRecordExportable($record_exportable)
    {
        if (is_null($record_exportable)) {
            throw new \InvalidArgumentException('non-nullable record_exportable cannot be null');
        }
        $this->container['record_exportable'] = $record_exportable;

        return $this;
    }

    /**
     * Gets record_importable
     *
     * @return bool|null
     */
    public function getRecordImportable()
    {
        return $this->container['record_importable'];
    }

    /**
     * Sets record_importable
     *
     * @param bool|null $record_importable The record import permission of the entity - true: Records are importable. - false: Records are not importable.
     *
     * @return self
     */
    public function setRecordImportable($record_importable)
    {
        if (is_null($record_importable)) {
            throw new \InvalidArgumentException('non-nullable record_importable cannot be null');
        }
        $this->container['record_importable'] = $record_importable;

        return $this;
    }

    /**
     * Gets record_viewable
     *
     * @return bool|null
     */
    public function getRecordViewable()
    {
        return $this->container['record_viewable'];
    }

    /**
     * Sets record_viewable
     *
     * @param bool|null $record_viewable The record view permission of the entity. - true: Records are viewable. - false: Records are not viewable.
     *
     * @return self
     */
    public function setRecordViewable($record_viewable)
    {
        if (is_null($record_viewable)) {
            throw new \InvalidArgumentException('non-nullable record_viewable cannot be null');
        }
        $this->container['record_viewable'] = $record_viewable;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


