<?php
/**
 * AppNotificationsGeneralGetNotification
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Kintone
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * REST API SPEC
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20250423000000
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Kintone\Model;

use \ArrayAccess;
use \Kintone\ObjectSerializer;

/**
 * AppNotificationsGeneralGetNotification Class Doc Comment
 *
 * @category Class
 * @package  Kintone
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AppNotificationsGeneralGetNotification implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AppNotificationsGeneralGetNotification';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'comment_added' => 'bool',
        'entity' => '\Kintone\Model\AppNotificationsGeneralGetNotificationEntity',
        'file_imported' => 'bool',
        'include_subs' => 'bool',
        'record_added' => 'bool',
        'record_edited' => 'bool',
        'status_changed' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'comment_added' => null,
        'entity' => null,
        'file_imported' => null,
        'include_subs' => null,
        'record_added' => null,
        'record_edited' => null,
        'status_changed' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'comment_added' => false,
        'entity' => false,
        'file_imported' => false,
        'include_subs' => false,
        'record_added' => false,
        'record_edited' => false,
        'status_changed' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'comment_added' => 'commentAdded',
        'entity' => 'entity',
        'file_imported' => 'fileImported',
        'include_subs' => 'includeSubs',
        'record_added' => 'recordAdded',
        'record_edited' => 'recordEdited',
        'status_changed' => 'statusChanged'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'comment_added' => 'setCommentAdded',
        'entity' => 'setEntity',
        'file_imported' => 'setFileImported',
        'include_subs' => 'setIncludeSubs',
        'record_added' => 'setRecordAdded',
        'record_edited' => 'setRecordEdited',
        'status_changed' => 'setStatusChanged'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'comment_added' => 'getCommentAdded',
        'entity' => 'getEntity',
        'file_imported' => 'getFileImported',
        'include_subs' => 'getIncludeSubs',
        'record_added' => 'getRecordAdded',
        'record_edited' => 'getRecordEdited',
        'status_changed' => 'getStatusChanged'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('comment_added', $data ?? [], null);
        $this->setIfExists('entity', $data ?? [], null);
        $this->setIfExists('file_imported', $data ?? [], null);
        $this->setIfExists('include_subs', $data ?? [], null);
        $this->setIfExists('record_added', $data ?? [], null);
        $this->setIfExists('record_edited', $data ?? [], null);
        $this->setIfExists('status_changed', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets comment_added
     *
     * @return bool|null
     */
    public function getCommentAdded()
    {
        return $this->container['comment_added'];
    }

    /**
     * Sets comment_added
     *
     * @param bool|null $comment_added Option to notify the entity when a comment is posted. - true: Notify when a comment is posted - false: Do not notify when a comment is posted
     *
     * @return self
     */
    public function setCommentAdded($comment_added)
    {
        if (is_null($comment_added)) {
            throw new \InvalidArgumentException('non-nullable comment_added cannot be null');
        }
        $this->container['comment_added'] = $comment_added;

        return $this;
    }

    /**
     * Gets entity
     *
     * @return \Kintone\Model\AppNotificationsGeneralGetNotificationEntity|null
     */
    public function getEntity()
    {
        return $this->container['entity'];
    }

    /**
     * Sets entity
     *
     * @param \Kintone\Model\AppNotificationsGeneralGetNotificationEntity|null $entity entity
     *
     * @return self
     */
    public function setEntity($entity)
    {
        if (is_null($entity)) {
            throw new \InvalidArgumentException('non-nullable entity cannot be null');
        }
        $this->container['entity'] = $entity;

        return $this;
    }

    /**
     * Gets file_imported
     *
     * @return bool|null
     */
    public function getFileImported()
    {
        return $this->container['file_imported'];
    }

    /**
     * Sets file_imported
     *
     * @param bool|null $file_imported Option to notify the entity when a file is imported. - true: Notify when a file is imported - false: Do not notify when a file is imported
     *
     * @return self
     */
    public function setFileImported($file_imported)
    {
        if (is_null($file_imported)) {
            throw new \InvalidArgumentException('non-nullable file_imported cannot be null');
        }
        $this->container['file_imported'] = $file_imported;

        return $this;
    }

    /**
     * Gets include_subs
     *
     * @return bool|null
     */
    public function getIncludeSubs()
    {
        return $this->container['include_subs'];
    }

    /**
     * Sets include_subs
     *
     * @param bool|null $include_subs The \"Include affiliated departments\" setting of the Department. Will always return `false` unless the notifications[].entity.type is set to `ORGANIZATION` or `FIELD_ENTITY` for a Department Selection Field. - true: Affiliated departments do inherit the General Notification settings - false: Affiliated departments do not inherit the General Notification settings
     *
     * @return self
     */
    public function setIncludeSubs($include_subs)
    {
        if (is_null($include_subs)) {
            throw new \InvalidArgumentException('non-nullable include_subs cannot be null');
        }
        $this->container['include_subs'] = $include_subs;

        return $this;
    }

    /**
     * Gets record_added
     *
     * @return bool|null
     */
    public function getRecordAdded()
    {
        return $this->container['record_added'];
    }

    /**
     * Sets record_added
     *
     * @param bool|null $record_added Option to notify the entity when a record is added. - true: Notify when a record is added - false: Do not notify when a record is added
     *
     * @return self
     */
    public function setRecordAdded($record_added)
    {
        if (is_null($record_added)) {
            throw new \InvalidArgumentException('non-nullable record_added cannot be null');
        }
        $this->container['record_added'] = $record_added;

        return $this;
    }

    /**
     * Gets record_edited
     *
     * @return bool|null
     */
    public function getRecordEdited()
    {
        return $this->container['record_edited'];
    }

    /**
     * Sets record_edited
     *
     * @param bool|null $record_edited Option to notify the entity when a record is edited. - true: Notify when a record is edited - false: Do not notify when a record is edited
     *
     * @return self
     */
    public function setRecordEdited($record_edited)
    {
        if (is_null($record_edited)) {
            throw new \InvalidArgumentException('non-nullable record_edited cannot be null');
        }
        $this->container['record_edited'] = $record_edited;

        return $this;
    }

    /**
     * Gets status_changed
     *
     * @return bool|null
     */
    public function getStatusChanged()
    {
        return $this->container['status_changed'];
    }

    /**
     * Sets status_changed
     *
     * @param bool|null $status_changed Option to notify the entity when a status is changed. - true: Notify when a status is changed - false: Do not notify when a status is changed
     *
     * @return self
     */
    public function setStatusChanged($status_changed)
    {
        if (is_null($status_changed)) {
            throw new \InvalidArgumentException('non-nullable status_changed cannot be null');
        }
        $this->container['status_changed'] = $status_changed;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


