<?php
/**
 * AppsStatisticsGetAppForm
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Kintone
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * REST API SPEC
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20250423000000
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Kintone\Model;

use \ArrayAccess;
use \Kintone\ObjectSerializer;

/**
 * AppsStatisticsGetAppForm Class Doc Comment
 *
 * @category Class
 * @package  Kintone
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AppsStatisticsGetAppForm implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AppsStatisticsGetAppForm';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'app_group' => 'string',
        'created_at' => '\DateTime',
        'creator' => '\Kintone\Model\AppsStatisticsGetAppFormCreator',
        'customized' => 'bool',
        'daily_request_count' => 'int',
        'field_count' => 'int',
        'id' => 'int',
        'modified_at' => '\DateTime',
        'modifier' => '\Kintone\Model\GetAppForGuestSpaceResponseModifier',
        'name' => 'string',
        'record_count' => 'int',
        'record_updated_at' => '\DateTime',
        'space' => '\Kintone\Model\AppsStatisticsGetAppFormSpace',
        'status' => 'string',
        'storage_usage' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'app_group' => null,
        'created_at' => 'date-time',
        'creator' => null,
        'customized' => null,
        'daily_request_count' => 'long',
        'field_count' => 'long',
        'id' => 'long',
        'modified_at' => 'date-time',
        'modifier' => null,
        'name' => null,
        'record_count' => 'long',
        'record_updated_at' => 'date-time',
        'space' => null,
        'status' => null,
        'storage_usage' => 'long'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'app_group' => false,
        'created_at' => false,
        'creator' => false,
        'customized' => false,
        'daily_request_count' => false,
        'field_count' => false,
        'id' => false,
        'modified_at' => false,
        'modifier' => false,
        'name' => false,
        'record_count' => false,
        'record_updated_at' => false,
        'space' => false,
        'status' => false,
        'storage_usage' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'app_group' => 'appGroup',
        'created_at' => 'createdAt',
        'creator' => 'creator',
        'customized' => 'customized',
        'daily_request_count' => 'dailyRequestCount',
        'field_count' => 'fieldCount',
        'id' => 'id',
        'modified_at' => 'modifiedAt',
        'modifier' => 'modifier',
        'name' => 'name',
        'record_count' => 'recordCount',
        'record_updated_at' => 'recordUpdatedAt',
        'space' => 'space',
        'status' => 'status',
        'storage_usage' => 'storageUsage'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'app_group' => 'setAppGroup',
        'created_at' => 'setCreatedAt',
        'creator' => 'setCreator',
        'customized' => 'setCustomized',
        'daily_request_count' => 'setDailyRequestCount',
        'field_count' => 'setFieldCount',
        'id' => 'setId',
        'modified_at' => 'setModifiedAt',
        'modifier' => 'setModifier',
        'name' => 'setName',
        'record_count' => 'setRecordCount',
        'record_updated_at' => 'setRecordUpdatedAt',
        'space' => 'setSpace',
        'status' => 'setStatus',
        'storage_usage' => 'setStorageUsage'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'app_group' => 'getAppGroup',
        'created_at' => 'getCreatedAt',
        'creator' => 'getCreator',
        'customized' => 'getCustomized',
        'daily_request_count' => 'getDailyRequestCount',
        'field_count' => 'getFieldCount',
        'id' => 'getId',
        'modified_at' => 'getModifiedAt',
        'modifier' => 'getModifier',
        'name' => 'getName',
        'record_count' => 'getRecordCount',
        'record_updated_at' => 'getRecordUpdatedAt',
        'space' => 'getSpace',
        'status' => 'getStatus',
        'storage_usage' => 'getStorageUsage'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const STATUS_NOT_ACTIVATED = 'NOT_ACTIVATED';
    public const STATUS_ACTIVATED = 'ACTIVATED';
    public const STATUS_CHANGED = 'CHANGED';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStatusAllowableValues()
    {
        return [
            self::STATUS_NOT_ACTIVATED,
            self::STATUS_ACTIVATED,
            self::STATUS_CHANGED,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('app_group', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('creator', $data ?? [], null);
        $this->setIfExists('customized', $data ?? [], null);
        $this->setIfExists('daily_request_count', $data ?? [], null);
        $this->setIfExists('field_count', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('modified_at', $data ?? [], null);
        $this->setIfExists('modifier', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('record_count', $data ?? [], null);
        $this->setIfExists('record_updated_at', $data ?? [], null);
        $this->setIfExists('space', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('storage_usage', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getStatusAllowableValues();
        if (!is_null($this->container['status']) && !in_array($this->container['status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'status', must be one of '%s'",
                $this->container['status'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets app_group
     *
     * @return string|null
     */
    public function getAppGroup()
    {
        return $this->container['app_group'];
    }

    /**
     * Sets app_group
     *
     * @param string|null $app_group The App Group.
     *
     * @return self
     */
    public function setAppGroup($app_group)
    {
        if (is_null($app_group)) {
            throw new \InvalidArgumentException('non-nullable app_group cannot be null');
        }
        $this->container['app_group'] = $app_group;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime|null
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime|null $created_at The date the App was created.
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets creator
     *
     * @return \Kintone\Model\AppsStatisticsGetAppFormCreator|null
     */
    public function getCreator()
    {
        return $this->container['creator'];
    }

    /**
     * Sets creator
     *
     * @param \Kintone\Model\AppsStatisticsGetAppFormCreator|null $creator creator
     *
     * @return self
     */
    public function setCreator($creator)
    {
        if (is_null($creator)) {
            throw new \InvalidArgumentException('non-nullable creator cannot be null');
        }
        $this->container['creator'] = $creator;

        return $this;
    }

    /**
     * Gets customized
     *
     * @return bool|null
     */
    public function getCustomized()
    {
        return $this->container['customized'];
    }

    /**
     * Sets customized
     *
     * @param bool|null $customized Whether the app is customized or not. Returns `true` if any of the following apply: - Customization by JavaScript / CSS - Customization by plugins - A list of \"customization\" formats exists
     *
     * @return self
     */
    public function setCustomized($customized)
    {
        if (is_null($customized)) {
            throw new \InvalidArgumentException('non-nullable customized cannot be null');
        }
        $this->container['customized'] = $customized;

        return $this;
    }

    /**
     * Gets daily_request_count
     *
     * @return int|null
     */
    public function getDailyRequestCount()
    {
        return $this->container['daily_request_count'];
    }

    /**
     * Sets daily_request_count
     *
     * @param int|null $daily_request_count The number of daily API requests.
     *
     * @return self
     */
    public function setDailyRequestCount($daily_request_count)
    {
        if (is_null($daily_request_count)) {
            throw new \InvalidArgumentException('non-nullable daily_request_count cannot be null');
        }
        $this->container['daily_request_count'] = $daily_request_count;

        return $this;
    }

    /**
     * Gets field_count
     *
     * @return int|null
     */
    public function getFieldCount()
    {
        return $this->container['field_count'];
    }

    /**
     * Sets field_count
     *
     * @param int|null $field_count The number of fields in the App.
     *
     * @return self
     */
    public function setFieldCount($field_count)
    {
        if (is_null($field_count)) {
            throw new \InvalidArgumentException('non-nullable field_count cannot be null');
        }
        $this->container['field_count'] = $field_count;

        return $this;
    }

    /**
     * Gets id
     *
     * @return int|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int|null $id The App ID
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets modified_at
     *
     * @return \DateTime|null
     */
    public function getModifiedAt()
    {
        return $this->container['modified_at'];
    }

    /**
     * Sets modified_at
     *
     * @param \DateTime|null $modified_at The date the App was last modified.
     *
     * @return self
     */
    public function setModifiedAt($modified_at)
    {
        if (is_null($modified_at)) {
            throw new \InvalidArgumentException('non-nullable modified_at cannot be null');
        }
        $this->container['modified_at'] = $modified_at;

        return $this;
    }

    /**
     * Gets modifier
     *
     * @return \Kintone\Model\GetAppForGuestSpaceResponseModifier|null
     */
    public function getModifier()
    {
        return $this->container['modifier'];
    }

    /**
     * Sets modifier
     *
     * @param \Kintone\Model\GetAppForGuestSpaceResponseModifier|null $modifier modifier
     *
     * @return self
     */
    public function setModifier($modifier)
    {
        if (is_null($modifier)) {
            throw new \InvalidArgumentException('non-nullable modifier cannot be null');
        }
        $this->container['modifier'] = $modifier;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name The name of the App. If Localization settings are enabled, the localized name will be returned. The localization language will be dependent on the language settings of the Kintone user authenticating this API.
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets record_count
     *
     * @return int|null
     */
    public function getRecordCount()
    {
        return $this->container['record_count'];
    }

    /**
     * Sets record_count
     *
     * @param int|null $record_count The number of records in the App.
     *
     * @return self
     */
    public function setRecordCount($record_count)
    {
        if (is_null($record_count)) {
            throw new \InvalidArgumentException('non-nullable record_count cannot be null');
        }
        $this->container['record_count'] = $record_count;

        return $this;
    }

    /**
     * Gets record_updated_at
     *
     * @return \DateTime|null
     */
    public function getRecordUpdatedAt()
    {
        return $this->container['record_updated_at'];
    }

    /**
     * Sets record_updated_at
     *
     * @param \DateTime|null $record_updated_at Date of last record added or edited. For apps that were created before the January 2021 update and have never had a record added or edited, the app creation date is returned.
     *
     * @return self
     */
    public function setRecordUpdatedAt($record_updated_at)
    {
        if (is_null($record_updated_at)) {
            throw new \InvalidArgumentException('non-nullable record_updated_at cannot be null');
        }
        $this->container['record_updated_at'] = $record_updated_at;

        return $this;
    }

    /**
     * Gets space
     *
     * @return \Kintone\Model\AppsStatisticsGetAppFormSpace|null
     */
    public function getSpace()
    {
        return $this->container['space'];
    }

    /**
     * Sets space
     *
     * @param \Kintone\Model\AppsStatisticsGetAppFormSpace|null $space space
     *
     * @return self
     */
    public function setSpace($space)
    {
        if (is_null($space)) {
            throw new \InvalidArgumentException('non-nullable space cannot be null');
        }
        $this->container['space'] = $space;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status The App status.
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $allowedValues = $this->getStatusAllowableValues();
        if (!in_array($status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'status', must be one of '%s'",
                    $status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets storage_usage
     *
     * @return int|null
     */
    public function getStorageUsage()
    {
        return $this->container['storage_usage'];
    }

    /**
     * Sets storage_usage
     *
     * @param int|null $storage_usage Total size of files attached in the Attachment field. Units are in Bytes.
     *
     * @return self
     */
    public function setStorageUsage($storage_usage)
    {
        if (is_null($storage_usage)) {
            throw new \InvalidArgumentException('non-nullable storage_usage cannot be null');
        }
        $this->container['storage_usage'] = $storage_usage;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


