<?php
/**
 * GuestsPostGuestUserForm
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Kintone
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * REST API SPEC
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20250423000000
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Kintone\Model;

use \ArrayAccess;
use \Kintone\ObjectSerializer;

/**
 * GuestsPostGuestUserForm Class Doc Comment
 *
 * @category Class
 * @package  Kintone
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GuestsPostGuestUserForm implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'GuestsPostGuestUserForm';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'callto' => 'string',
        'code' => 'string',
        'company' => 'string',
        'division' => 'string',
        'given_name_reading' => 'string',
        'image' => 'string',
        'locale' => 'string',
        'name' => 'string',
        'password' => 'string',
        'phone' => 'string',
        'sur_name_reading' => 'string',
        'timezone' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'callto' => null,
        'code' => 'email',
        'company' => null,
        'division' => null,
        'given_name_reading' => null,
        'image' => null,
        'locale' => 'locale',
        'name' => null,
        'password' => null,
        'phone' => null,
        'sur_name_reading' => null,
        'timezone' => 'timezone'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'callto' => false,
        'code' => false,
        'company' => false,
        'division' => false,
        'given_name_reading' => false,
        'image' => false,
        'locale' => false,
        'name' => false,
        'password' => false,
        'phone' => false,
        'sur_name_reading' => false,
        'timezone' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'callto' => 'callto',
        'code' => 'code',
        'company' => 'company',
        'division' => 'division',
        'given_name_reading' => 'givenNameReading',
        'image' => 'image',
        'locale' => 'locale',
        'name' => 'name',
        'password' => 'password',
        'phone' => 'phone',
        'sur_name_reading' => 'surNameReading',
        'timezone' => 'timezone'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'callto' => 'setCallto',
        'code' => 'setCode',
        'company' => 'setCompany',
        'division' => 'setDivision',
        'given_name_reading' => 'setGivenNameReading',
        'image' => 'setImage',
        'locale' => 'setLocale',
        'name' => 'setName',
        'password' => 'setPassword',
        'phone' => 'setPhone',
        'sur_name_reading' => 'setSurNameReading',
        'timezone' => 'setTimezone'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'callto' => 'getCallto',
        'code' => 'getCode',
        'company' => 'getCompany',
        'division' => 'getDivision',
        'given_name_reading' => 'getGivenNameReading',
        'image' => 'getImage',
        'locale' => 'getLocale',
        'name' => 'getName',
        'password' => 'getPassword',
        'phone' => 'getPhone',
        'sur_name_reading' => 'getSurNameReading',
        'timezone' => 'getTimezone'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('callto', $data ?? [], null);
        $this->setIfExists('code', $data ?? [], null);
        $this->setIfExists('company', $data ?? [], null);
        $this->setIfExists('division', $data ?? [], null);
        $this->setIfExists('given_name_reading', $data ?? [], null);
        $this->setIfExists('image', $data ?? [], null);
        $this->setIfExists('locale', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('password', $data ?? [], null);
        $this->setIfExists('phone', $data ?? [], null);
        $this->setIfExists('sur_name_reading', $data ?? [], null);
        $this->setIfExists('timezone', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['callto']) && (mb_strlen($this->container['callto']) > 256)) {
            $invalidProperties[] = "invalid value for 'callto', the character length must be smaller than or equal to 256.";
        }

        if ($this->container['code'] === null) {
            $invalidProperties[] = "'code' can't be null";
        }
        if (!is_null($this->container['company']) && (mb_strlen($this->container['company']) > 100)) {
            $invalidProperties[] = "invalid value for 'company', the character length must be smaller than or equal to 100.";
        }

        if (!is_null($this->container['division']) && (mb_strlen($this->container['division']) > 100)) {
            $invalidProperties[] = "invalid value for 'division', the character length must be smaller than or equal to 100.";
        }

        if (!is_null($this->container['given_name_reading']) && (mb_strlen($this->container['given_name_reading']) > 64)) {
            $invalidProperties[] = "invalid value for 'given_name_reading', the character length must be smaller than or equal to 64.";
        }

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ((mb_strlen($this->container['name']) > 128)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be smaller than or equal to 128.";
        }

        if ((mb_strlen($this->container['name']) < 1)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['password'] === null) {
            $invalidProperties[] = "'password' can't be null";
        }
        if ((mb_strlen($this->container['password']) > 64)) {
            $invalidProperties[] = "invalid value for 'password', the character length must be smaller than or equal to 64.";
        }

        if ((mb_strlen($this->container['password']) < 3)) {
            $invalidProperties[] = "invalid value for 'password', the character length must be bigger than or equal to 3.";
        }

        if (!is_null($this->container['phone']) && (mb_strlen($this->container['phone']) > 100)) {
            $invalidProperties[] = "invalid value for 'phone', the character length must be smaller than or equal to 100.";
        }

        if (!is_null($this->container['sur_name_reading']) && (mb_strlen($this->container['sur_name_reading']) > 64)) {
            $invalidProperties[] = "invalid value for 'sur_name_reading', the character length must be smaller than or equal to 64.";
        }

        if ($this->container['timezone'] === null) {
            $invalidProperties[] = "'timezone' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets callto
     *
     * @return string|null
     */
    public function getCallto()
    {
        return $this->container['callto'];
    }

    /**
     * Sets callto
     *
     * @param string|null $callto The Skype Name of the Guest user. The maximum limit is 256 characters.
     *
     * @return self
     */
    public function setCallto($callto)
    {
        if (is_null($callto)) {
            throw new \InvalidArgumentException('non-nullable callto cannot be null');
        }
        if ((mb_strlen($callto) > 256)) {
            throw new \InvalidArgumentException('invalid length for $callto when calling GuestsPostGuestUserForm., must be smaller than or equal to 256.');
        }

        $this->container['callto'] = $callto;

        return $this;
    }

    /**
     * Gets code
     *
     * @return string
     */
    public function getCode()
    {
        return $this->container['code'];
    }

    /**
     * Sets code
     *
     * @param string $code The email address (log in name) of the Guest user.
     *
     * @return self
     */
    public function setCode($code)
    {
        if (is_null($code)) {
            throw new \InvalidArgumentException('non-nullable code cannot be null');
        }
        $this->container['code'] = $code;

        return $this;
    }

    /**
     * Gets company
     *
     * @return string|null
     */
    public function getCompany()
    {
        return $this->container['company'];
    }

    /**
     * Sets company
     *
     * @param string|null $company The Company name to display on the Guest User's profile. The maximum limit is 100 characters.
     *
     * @return self
     */
    public function setCompany($company)
    {
        if (is_null($company)) {
            throw new \InvalidArgumentException('non-nullable company cannot be null');
        }
        if ((mb_strlen($company) > 100)) {
            throw new \InvalidArgumentException('invalid length for $company when calling GuestsPostGuestUserForm., must be smaller than or equal to 100.');
        }

        $this->container['company'] = $company;

        return $this;
    }

    /**
     * Gets division
     *
     * @return string|null
     */
    public function getDivision()
    {
        return $this->container['division'];
    }

    /**
     * Sets division
     *
     * @param string|null $division The Department name to display on the Guest User's profile. The maximum limit is 100 characters.
     *
     * @return self
     */
    public function setDivision($division)
    {
        if (is_null($division)) {
            throw new \InvalidArgumentException('non-nullable division cannot be null');
        }
        if ((mb_strlen($division) > 100)) {
            throw new \InvalidArgumentException('invalid length for $division when calling GuestsPostGuestUserForm., must be smaller than or equal to 100.');
        }

        $this->container['division'] = $division;

        return $this;
    }

    /**
     * Gets given_name_reading
     *
     * @return string|null
     */
    public function getGivenNameReading()
    {
        return $this->container['given_name_reading'];
    }

    /**
     * Sets given_name_reading
     *
     * @param string|null $given_name_reading The Phonetic Given Name settings of the Guest User. The maximum limit is 64 characters.
     *
     * @return self
     */
    public function setGivenNameReading($given_name_reading)
    {
        if (is_null($given_name_reading)) {
            throw new \InvalidArgumentException('non-nullable given_name_reading cannot be null');
        }
        if ((mb_strlen($given_name_reading) > 64)) {
            throw new \InvalidArgumentException('invalid length for $given_name_reading when calling GuestsPostGuestUserForm., must be smaller than or equal to 64.');
        }

        $this->container['given_name_reading'] = $given_name_reading;

        return $this;
    }

    /**
     * Gets image
     *
     * @return string|null
     */
    public function getImage()
    {
        return $this->container['image'];
    }

    /**
     * Sets image
     *
     * @param string|null $image The profile image of the Guest user. Specify a fileKey of an uploaded file. fileKeys can be found from the response of the Upload File API. If ignored, a default image will be set.
     *
     * @return self
     */
    public function setImage($image)
    {
        if (is_null($image)) {
            throw new \InvalidArgumentException('non-nullable image cannot be null');
        }
        $this->container['image'] = $image;

        return $this;
    }

    /**
     * Gets locale
     *
     * @return string|null
     */
    public function getLocale()
    {
        return $this->container['locale'];
    }

    /**
     * Sets locale
     *
     * @param string|null $locale The language settings of the Guest user. - auto: Use web browser settings. - en: English - zh: Chinese - ja: Japanese If ignored, auto will be set.
     *
     * @return self
     */
    public function setLocale($locale)
    {
        if (is_null($locale)) {
            throw new \InvalidArgumentException('non-nullable locale cannot be null');
        }
        $this->container['locale'] = $locale;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name The display name of the user. Must be between 1 - 128 characters.
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        if ((mb_strlen($name) > 128)) {
            throw new \InvalidArgumentException('invalid length for $name when calling GuestsPostGuestUserForm., must be smaller than or equal to 128.');
        }
        if ((mb_strlen($name) < 1)) {
            throw new \InvalidArgumentException('invalid length for $name when calling GuestsPostGuestUserForm., must be bigger than or equal to 1.');
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets password
     *
     * @return string
     */
    public function getPassword()
    {
        return $this->container['password'];
    }

    /**
     * Sets password
     *
     * @param string $password The log in password of the Guest user.
     *
     * @return self
     */
    public function setPassword($password)
    {
        if (is_null($password)) {
            throw new \InvalidArgumentException('non-nullable password cannot be null');
        }
        if ((mb_strlen($password) > 64)) {
            throw new \InvalidArgumentException('invalid length for $password when calling GuestsPostGuestUserForm., must be smaller than or equal to 64.');
        }
        if ((mb_strlen($password) < 3)) {
            throw new \InvalidArgumentException('invalid length for $password when calling GuestsPostGuestUserForm., must be bigger than or equal to 3.');
        }

        $this->container['password'] = $password;

        return $this;
    }

    /**
     * Gets phone
     *
     * @return string|null
     */
    public function getPhone()
    {
        return $this->container['phone'];
    }

    /**
     * Sets phone
     *
     * @param string|null $phone The Phone number to display on the Guest User's profile. The maximum limit is 100 characters.
     *
     * @return self
     */
    public function setPhone($phone)
    {
        if (is_null($phone)) {
            throw new \InvalidArgumentException('non-nullable phone cannot be null');
        }
        if ((mb_strlen($phone) > 100)) {
            throw new \InvalidArgumentException('invalid length for $phone when calling GuestsPostGuestUserForm., must be smaller than or equal to 100.');
        }

        $this->container['phone'] = $phone;

        return $this;
    }

    /**
     * Gets sur_name_reading
     *
     * @return string|null
     */
    public function getSurNameReading()
    {
        return $this->container['sur_name_reading'];
    }

    /**
     * Sets sur_name_reading
     *
     * @param string|null $sur_name_reading The Phonetic Surname settings of the Guest User. The maximum limit is 64 characters.
     *
     * @return self
     */
    public function setSurNameReading($sur_name_reading)
    {
        if (is_null($sur_name_reading)) {
            throw new \InvalidArgumentException('non-nullable sur_name_reading cannot be null');
        }
        if ((mb_strlen($sur_name_reading) > 64)) {
            throw new \InvalidArgumentException('invalid length for $sur_name_reading when calling GuestsPostGuestUserForm., must be smaller than or equal to 64.');
        }

        $this->container['sur_name_reading'] = $sur_name_reading;

        return $this;
    }

    /**
     * Gets timezone
     *
     * @return string
     */
    public function getTimezone()
    {
        return $this->container['timezone'];
    }

    /**
     * Sets timezone
     *
     * @param string $timezone The timezone of the Guest user.
     *
     * @return self
     */
    public function setTimezone($timezone)
    {
        if (is_null($timezone)) {
            throw new \InvalidArgumentException('non-nullable timezone cannot be null');
        }
        $this->container['timezone'] = $timezone;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


