<?php
/**
 * PreviewAppFormFieldsPutDecimalFieldForm
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Kintone
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * REST API SPEC
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20250423000000
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Kintone\Model;

use \ArrayAccess;
use \Kintone\ObjectSerializer;

/**
 * PreviewAppFormFieldsPutDecimalFieldForm Class Doc Comment
 *
 * @category Class
 * @package  Kintone
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PreviewAppFormFieldsPutDecimalFieldForm implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'PreviewAppFormFieldsPutDecimalFieldForm';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'code' => 'string',
        'default_value' => 'string',
        'digit' => 'bool',
        'display_scale' => 'int',
        'label' => 'string',
        'max_value' => 'int',
        'min_value' => 'int',
        'no_label' => 'bool',
        'required' => 'bool',
        'type' => 'string',
        'unique' => 'bool',
        'unit' => 'string',
        'unit_position' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'code' => null,
        'default_value' => null,
        'digit' => 'boolean',
        'display_scale' => 'long',
        'label' => null,
        'max_value' => 'long',
        'min_value' => 'long',
        'no_label' => 'boolean',
        'required' => 'boolean',
        'type' => null,
        'unique' => 'boolean',
        'unit' => null,
        'unit_position' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'code' => false,
        'default_value' => false,
        'digit' => false,
        'display_scale' => false,
        'label' => false,
        'max_value' => false,
        'min_value' => false,
        'no_label' => false,
        'required' => false,
        'type' => false,
        'unique' => false,
        'unit' => false,
        'unit_position' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'code' => 'code',
        'default_value' => 'defaultValue',
        'digit' => 'digit',
        'display_scale' => 'displayScale',
        'label' => 'label',
        'max_value' => 'maxValue',
        'min_value' => 'minValue',
        'no_label' => 'noLabel',
        'required' => 'required',
        'type' => 'type',
        'unique' => 'unique',
        'unit' => 'unit',
        'unit_position' => 'unitPosition'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'code' => 'setCode',
        'default_value' => 'setDefaultValue',
        'digit' => 'setDigit',
        'display_scale' => 'setDisplayScale',
        'label' => 'setLabel',
        'max_value' => 'setMaxValue',
        'min_value' => 'setMinValue',
        'no_label' => 'setNoLabel',
        'required' => 'setRequired',
        'type' => 'setType',
        'unique' => 'setUnique',
        'unit' => 'setUnit',
        'unit_position' => 'setUnitPosition'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'code' => 'getCode',
        'default_value' => 'getDefaultValue',
        'digit' => 'getDigit',
        'display_scale' => 'getDisplayScale',
        'label' => 'getLabel',
        'max_value' => 'getMaxValue',
        'min_value' => 'getMinValue',
        'no_label' => 'getNoLabel',
        'required' => 'getRequired',
        'type' => 'getType',
        'unique' => 'getUnique',
        'unit' => 'getUnit',
        'unit_position' => 'getUnitPosition'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const TYPE_CALC = 'CALC';
    public const TYPE_CATEGORY = 'CATEGORY';
    public const TYPE_CHECK_BOX = 'CHECK_BOX';
    public const TYPE_CREATED_TIME = 'CREATED_TIME';
    public const TYPE_CREATOR = 'CREATOR';
    public const TYPE_DATE = 'DATE';
    public const TYPE_DATETIME = 'DATETIME';
    public const TYPE_DROP_DOWN = 'DROP_DOWN';
    public const TYPE_FILE = 'FILE';
    public const TYPE_GROUP = 'GROUP';
    public const TYPE_GROUP_SELECT = 'GROUP_SELECT';
    public const TYPE_LINK = 'LINK';
    public const TYPE_MODIFIER = 'MODIFIER';
    public const TYPE_MULTI_LINE_TEXT = 'MULTI_LINE_TEXT';
    public const TYPE_MULTI_SELECT = 'MULTI_SELECT';
    public const TYPE_NUMBER = 'NUMBER';
    public const TYPE_ORGANIZATION_SELECT = 'ORGANIZATION_SELECT';
    public const TYPE_RADIO_BUTTON = 'RADIO_BUTTON';
    public const TYPE_RECORD_NUMBER = 'RECORD_NUMBER';
    public const TYPE_REFERENCE_TABLE = 'REFERENCE_TABLE';
    public const TYPE_RICH_TEXT = 'RICH_TEXT';
    public const TYPE_SINGLE_LINE_TEXT = 'SINGLE_LINE_TEXT';
    public const TYPE_STATUS = 'STATUS';
    public const TYPE_STATUS_ASSIGNEE = 'STATUS_ASSIGNEE';
    public const TYPE_SUBTABLE = 'SUBTABLE';
    public const TYPE_TIME = 'TIME';
    public const TYPE_UPDATED_TIME = 'UPDATED_TIME';
    public const TYPE_USER_SELECT = 'USER_SELECT';
    public const UNIT_POSITION_BEFORE = 'BEFORE';
    public const UNIT_POSITION_AFTER = 'AFTER';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTypeAllowableValues()
    {
        return [
            self::TYPE_CALC,
            self::TYPE_CATEGORY,
            self::TYPE_CHECK_BOX,
            self::TYPE_CREATED_TIME,
            self::TYPE_CREATOR,
            self::TYPE_DATE,
            self::TYPE_DATETIME,
            self::TYPE_DROP_DOWN,
            self::TYPE_FILE,
            self::TYPE_GROUP,
            self::TYPE_GROUP_SELECT,
            self::TYPE_LINK,
            self::TYPE_MODIFIER,
            self::TYPE_MULTI_LINE_TEXT,
            self::TYPE_MULTI_SELECT,
            self::TYPE_NUMBER,
            self::TYPE_ORGANIZATION_SELECT,
            self::TYPE_RADIO_BUTTON,
            self::TYPE_RECORD_NUMBER,
            self::TYPE_REFERENCE_TABLE,
            self::TYPE_RICH_TEXT,
            self::TYPE_SINGLE_LINE_TEXT,
            self::TYPE_STATUS,
            self::TYPE_STATUS_ASSIGNEE,
            self::TYPE_SUBTABLE,
            self::TYPE_TIME,
            self::TYPE_UPDATED_TIME,
            self::TYPE_USER_SELECT,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getUnitPositionAllowableValues()
    {
        return [
            self::UNIT_POSITION_BEFORE,
            self::UNIT_POSITION_AFTER,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('code', $data ?? [], null);
        $this->setIfExists('default_value', $data ?? [], null);
        $this->setIfExists('digit', $data ?? [], null);
        $this->setIfExists('display_scale', $data ?? [], null);
        $this->setIfExists('label', $data ?? [], null);
        $this->setIfExists('max_value', $data ?? [], null);
        $this->setIfExists('min_value', $data ?? [], null);
        $this->setIfExists('no_label', $data ?? [], null);
        $this->setIfExists('required', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('unique', $data ?? [], null);
        $this->setIfExists('unit', $data ?? [], null);
        $this->setIfExists('unit_position', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['code']) && (mb_strlen($this->container['code']) > 128)) {
            $invalidProperties[] = "invalid value for 'code', the character length must be smaller than or equal to 128.";
        }

        if (!is_null($this->container['code']) && (mb_strlen($this->container['code']) < 1)) {
            $invalidProperties[] = "invalid value for 'code', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['default_value']) && (mb_strlen($this->container['default_value']) > 1000)) {
            $invalidProperties[] = "invalid value for 'default_value', the character length must be smaller than or equal to 1000.";
        }

        if (!is_null($this->container['label']) && (mb_strlen($this->container['label']) > 128)) {
            $invalidProperties[] = "invalid value for 'label', the character length must be smaller than or equal to 128.";
        }

        if (!is_null($this->container['label']) && (mb_strlen($this->container['label']) < 1)) {
            $invalidProperties[] = "invalid value for 'label', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['type'] === null) {
            $invalidProperties[] = "'type' can't be null";
        }
        $allowedValues = $this->getTypeAllowableValues();
        if (!is_null($this->container['type']) && !in_array($this->container['type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'type', must be one of '%s'",
                $this->container['type'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['unit']) && (mb_strlen($this->container['unit']) > 128)) {
            $invalidProperties[] = "invalid value for 'unit', the character length must be smaller than or equal to 128.";
        }

        $allowedValues = $this->getUnitPositionAllowableValues();
        if (!is_null($this->container['unit_position']) && !in_array($this->container['unit_position'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'unit_position', must be one of '%s'",
                $this->container['unit_position'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets code
     *
     * @return string|null
     */
    public function getCode()
    {
        return $this->container['code'];
    }

    /**
     * Sets code
     *
     * @param string|null $code The field code of the field. Field codes have the following limitations: - The maximum character limit is 128 - Duplicate field codes cannot exist - _ is the only symbol that can be used - Numbers cannot be used to start a field code
     *
     * @return self
     */
    public function setCode($code)
    {
        if (is_null($code)) {
            throw new \InvalidArgumentException('non-nullable code cannot be null');
        }
        if ((mb_strlen($code) > 128)) {
            throw new \InvalidArgumentException('invalid length for $code when calling PreviewAppFormFieldsPutDecimalFieldForm., must be smaller than or equal to 128.');
        }
        if ((mb_strlen($code) < 1)) {
            throw new \InvalidArgumentException('invalid length for $code when calling PreviewAppFormFieldsPutDecimalFieldForm., must be bigger than or equal to 1.');
        }

        $this->container['code'] = $code;

        return $this;
    }

    /**
     * Gets default_value
     *
     * @return string|null
     */
    public function getDefaultValue()
    {
        return $this->container['default_value'];
    }

    /**
     * Sets default_value
     *
     * @param string|null $default_value The default value. For fields that can set multiple default values, specify the value as an array. The defaultNowValue will take priority if it also specified. For User/Group/Department fields, an array of objects that include code and type are required. - properties.{fieldcode}.defaultValue[].code   State the code of the User/Group/Department, or the function \"LOGINUSER()\".Departments cannot be specified for Apps in Guest spaces. - properties.{fieldcode}.defaultValue[].type   State the type of the default value     - USER: User     - GROUP: Group     - ORGANIZATION: Department     - FUNCTION: Function
     *
     * @return self
     */
    public function setDefaultValue($default_value)
    {
        if (is_null($default_value)) {
            throw new \InvalidArgumentException('non-nullable default_value cannot be null');
        }
        if ((mb_strlen($default_value) > 1000)) {
            throw new \InvalidArgumentException('invalid length for $default_value when calling PreviewAppFormFieldsPutDecimalFieldForm., must be smaller than or equal to 1000.');
        }

        $this->container['default_value'] = $default_value;

        return $this;
    }

    /**
     * Gets digit
     *
     * @return bool|null
     */
    public function getDigit()
    {
        return $this->container['digit'];
    }

    /**
     * Sets digit
     *
     * @param bool|null $digit The \"Use thousands separators\" option. - true: Thousands separators will be displayed for the number. - false: Thousands separators will not be displayed for the number.
     *
     * @return self
     */
    public function setDigit($digit)
    {
        if (is_null($digit)) {
            throw new \InvalidArgumentException('non-nullable digit cannot be null');
        }
        $this->container['digit'] = $digit;

        return $this;
    }

    /**
     * Gets display_scale
     *
     * @return int|null
     */
    public function getDisplayScale()
    {
        return $this->container['display_scale'];
    }

    /**
     * Sets display_scale
     *
     * @param int|null $display_scale The number of decimal places to display for the field.
     *
     * @return self
     */
    public function setDisplayScale($display_scale)
    {
        if (is_null($display_scale)) {
            throw new \InvalidArgumentException('non-nullable display_scale cannot be null');
        }
        $this->container['display_scale'] = $display_scale;

        return $this;
    }

    /**
     * Gets label
     *
     * @return string|null
     */
    public function getLabel()
    {
        return $this->container['label'];
    }

    /**
     * Sets label
     *
     * @param string|null $label The field name.
     *
     * @return self
     */
    public function setLabel($label)
    {
        if (is_null($label)) {
            throw new \InvalidArgumentException('non-nullable label cannot be null');
        }
        if ((mb_strlen($label) > 128)) {
            throw new \InvalidArgumentException('invalid length for $label when calling PreviewAppFormFieldsPutDecimalFieldForm., must be smaller than or equal to 128.');
        }
        if ((mb_strlen($label) < 1)) {
            throw new \InvalidArgumentException('invalid length for $label when calling PreviewAppFormFieldsPutDecimalFieldForm., must be bigger than or equal to 1.');
        }

        $this->container['label'] = $label;

        return $this;
    }

    /**
     * Gets max_value
     *
     * @return int|null
     */
    public function getMaxValue()
    {
        return $this->container['max_value'];
    }

    /**
     * Sets max_value
     *
     * @param int|null $max_value The maximum number of characters for the field.
     *
     * @return self
     */
    public function setMaxValue($max_value)
    {
        if (is_null($max_value)) {
            throw new \InvalidArgumentException('non-nullable max_value cannot be null');
        }
        $this->container['max_value'] = $max_value;

        return $this;
    }

    /**
     * Gets min_value
     *
     * @return int|null
     */
    public function getMinValue()
    {
        return $this->container['min_value'];
    }

    /**
     * Sets min_value
     *
     * @param int|null $min_value The minimum number of characters for the field.
     *
     * @return self
     */
    public function setMinValue($min_value)
    {
        if (is_null($min_value)) {
            throw new \InvalidArgumentException('non-nullable min_value cannot be null');
        }
        $this->container['min_value'] = $min_value;

        return $this;
    }

    /**
     * Gets no_label
     *
     * @return bool|null
     */
    public function getNoLabel()
    {
        return $this->container['no_label'];
    }

    /**
     * Sets no_label
     *
     * @param bool|null $no_label The \"Hide field name\" option. - true: The field's name will be hidden. - false: The field's name will be displayed.
     *
     * @return self
     */
    public function setNoLabel($no_label)
    {
        if (is_null($no_label)) {
            throw new \InvalidArgumentException('non-nullable no_label cannot be null');
        }
        $this->container['no_label'] = $no_label;

        return $this;
    }

    /**
     * Gets required
     *
     * @return bool|null
     */
    public function getRequired()
    {
        return $this->container['required'];
    }

    /**
     * Sets required
     *
     * @param bool|null $required The \"Required field\" option. - true: The field will be a required field. - false: The field will not be a required field.
     *
     * @return self
     */
    public function setRequired($required)
    {
        if (is_null($required)) {
            throw new \InvalidArgumentException('non-nullable required cannot be null');
        }
        $this->container['required'] = $required;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type The field type. - GROUP: Group - GROUP_SELECT: Group selection - CALC: Calculated - CHECK_BOX: Check box - DATE: Date - DATETIME: Date and time - DROP_DOWN: Drop-down - FILE: Attachment - LINK: Link - MULTI_LINE_TEXT: Text Area - MULTI_SELECT: Multi-choice - NUMBER: Number - ORGANIZATION_SELECT: Department selection - RADIO_BUTTON: Radio button - RECORD_NUMBER: Record number - REFERENCE_TABLE: Related Records - RICH_TEXT: Rich text - SINGLE_LINE_TEXT: Text - SUBTABLE: Table - TIME: Time - USER_SELECT: User selection  For Lookup fields, specify either SINGLE_LINE_TEXT or NUMBER, depending on the type of the Key field it's looking up.
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $allowedValues = $this->getTypeAllowableValues();
        if (!in_array($type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'type', must be one of '%s'",
                    $type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets unique
     *
     * @return bool|null
     */
    public function getUnique()
    {
        return $this->container['unique'];
    }

    /**
     * Sets unique
     *
     * @param bool|null $unique The \"Prohibit duplicate values\" option. - true: Duplicate values will be prohibited. - false: Duplicate values will not be prohibited.
     *
     * @return self
     */
    public function setUnique($unique)
    {
        if (is_null($unique)) {
            throw new \InvalidArgumentException('non-nullable unique cannot be null');
        }
        $this->container['unique'] = $unique;

        return $this;
    }

    /**
     * Gets unit
     *
     * @return string|null
     */
    public function getUnit()
    {
        return $this->container['unit'];
    }

    /**
     * Sets unit
     *
     * @param string|null $unit The Currency settings of the field.
     *
     * @return self
     */
    public function setUnit($unit)
    {
        if (is_null($unit)) {
            throw new \InvalidArgumentException('non-nullable unit cannot be null');
        }
        if ((mb_strlen($unit) > 128)) {
            throw new \InvalidArgumentException('invalid length for $unit when calling PreviewAppFormFieldsPutDecimalFieldForm., must be smaller than or equal to 128.');
        }

        $this->container['unit'] = $unit;

        return $this;
    }

    /**
     * Gets unit_position
     *
     * @return string|null
     */
    public function getUnitPosition()
    {
        return $this->container['unit_position'];
    }

    /**
     * Sets unit_position
     *
     * @param string|null $unit_position The display position of the Currency. - BEFORE: The currency will be displayed before the field value. - AFTER: The currency will be displayed after the field value.
     *
     * @return self
     */
    public function setUnitPosition($unit_position)
    {
        if (is_null($unit_position)) {
            throw new \InvalidArgumentException('non-nullable unit_position cannot be null');
        }
        $allowedValues = $this->getUnitPositionAllowableValues();
        if (!in_array($unit_position, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'unit_position', must be one of '%s'",
                    $unit_position,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['unit_position'] = $unit_position;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


