<?php
/**
 * FIELDSApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Kintone
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * REST API SPEC
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20250423000000
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Kintone\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Kintone\ApiException;
use Kintone\Configuration;
use Kintone\FormDataProcessor;
use Kintone\HeaderSelector;
use Kintone\ObjectSerializer;

/**
 * FIELDSApi Class Doc Comment
 *
 * @category Class
 * @package  Kintone
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FIELDSApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getFieldAcl' => [
            'application/json',
        ],
        'getFieldAclForGuestSpace' => [
            'application/json',
        ],
        'getPreviewFieldAcl' => [
            'application/json',
        ],
        'getPreviewFieldAclForGuestSpace' => [
            'application/json',
        ],
        'putFieldAcl' => [
            'application/json',
        ],
        'putFieldAclForGuestSpace' => [
            'application/json',
        ],
        'putPreviewFieldAcl' => [
            'application/json',
        ],
        'putPreviewFieldAclForGuestSpace' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getFieldAcl
     *
     * @param  int $app The App ID. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getFieldAcl'] to see the possible values for this operation
     *
     * @throws \Kintone\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Kintone\Model\GetFieldAclResponse
     */
    public function getFieldAcl($app, string $contentType = self::contentTypes['getFieldAcl'][0])
    {
        list($response) = $this->getFieldAclWithHttpInfo($app, $contentType);
        return $response;
    }

    /**
     * Operation getFieldAclWithHttpInfo
     *
     * @param  int $app The App ID. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getFieldAcl'] to see the possible values for this operation
     *
     * @throws \Kintone\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Kintone\Model\GetFieldAclResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getFieldAclWithHttpInfo($app, string $contentType = self::contentTypes['getFieldAcl'][0])
    {
        $request = $this->getFieldAclRequest($app, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Kintone\Model\GetFieldAclResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Kintone\Model\GetFieldAclResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Kintone\Model\GetFieldAclResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getFieldAclAsync
     *
     * @param  int $app The App ID. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getFieldAcl'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getFieldAclAsync($app, string $contentType = self::contentTypes['getFieldAcl'][0])
    {
        return $this->getFieldAclAsyncWithHttpInfo($app, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getFieldAclAsyncWithHttpInfo
     *
     * @param  int $app The App ID. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getFieldAcl'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getFieldAclAsyncWithHttpInfo($app, string $contentType = self::contentTypes['getFieldAcl'][0])
    {
        $returnType = '\Kintone\Model\GetFieldAclResponse';
        $request = $this->getFieldAclRequest($app, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getFieldAcl'
     *
     * @param  int $app The App ID. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getFieldAcl'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getFieldAclRequest($app, string $contentType = self::contentTypes['getFieldAcl'][0])
    {

        // verify the required parameter 'app' is set
        if ($app === null || (is_array($app) && count($app) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $app when calling getFieldAcl'
            );
        }


        $resourcePath = '/k/v1/field/acl.json';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $app,
            'app', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getFieldAclForGuestSpace
     *
     * @param  int $guest_space_id guest space id (required)
     * @param  int $app The App ID. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getFieldAclForGuestSpace'] to see the possible values for this operation
     *
     * @throws \Kintone\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Kintone\Model\GetFieldAclForGuestSpaceResponse
     */
    public function getFieldAclForGuestSpace($guest_space_id, $app, string $contentType = self::contentTypes['getFieldAclForGuestSpace'][0])
    {
        list($response) = $this->getFieldAclForGuestSpaceWithHttpInfo($guest_space_id, $app, $contentType);
        return $response;
    }

    /**
     * Operation getFieldAclForGuestSpaceWithHttpInfo
     *
     * @param  int $guest_space_id guest space id (required)
     * @param  int $app The App ID. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getFieldAclForGuestSpace'] to see the possible values for this operation
     *
     * @throws \Kintone\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Kintone\Model\GetFieldAclForGuestSpaceResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getFieldAclForGuestSpaceWithHttpInfo($guest_space_id, $app, string $contentType = self::contentTypes['getFieldAclForGuestSpace'][0])
    {
        $request = $this->getFieldAclForGuestSpaceRequest($guest_space_id, $app, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Kintone\Model\GetFieldAclForGuestSpaceResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Kintone\Model\GetFieldAclForGuestSpaceResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Kintone\Model\GetFieldAclForGuestSpaceResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getFieldAclForGuestSpaceAsync
     *
     * @param  int $guest_space_id guest space id (required)
     * @param  int $app The App ID. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getFieldAclForGuestSpace'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getFieldAclForGuestSpaceAsync($guest_space_id, $app, string $contentType = self::contentTypes['getFieldAclForGuestSpace'][0])
    {
        return $this->getFieldAclForGuestSpaceAsyncWithHttpInfo($guest_space_id, $app, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getFieldAclForGuestSpaceAsyncWithHttpInfo
     *
     * @param  int $guest_space_id guest space id (required)
     * @param  int $app The App ID. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getFieldAclForGuestSpace'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getFieldAclForGuestSpaceAsyncWithHttpInfo($guest_space_id, $app, string $contentType = self::contentTypes['getFieldAclForGuestSpace'][0])
    {
        $returnType = '\Kintone\Model\GetFieldAclForGuestSpaceResponse';
        $request = $this->getFieldAclForGuestSpaceRequest($guest_space_id, $app, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getFieldAclForGuestSpace'
     *
     * @param  int $guest_space_id guest space id (required)
     * @param  int $app The App ID. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getFieldAclForGuestSpace'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getFieldAclForGuestSpaceRequest($guest_space_id, $app, string $contentType = self::contentTypes['getFieldAclForGuestSpace'][0])
    {

        // verify the required parameter 'guest_space_id' is set
        if ($guest_space_id === null || (is_array($guest_space_id) && count($guest_space_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $guest_space_id when calling getFieldAclForGuestSpace'
            );
        }

        // verify the required parameter 'app' is set
        if ($app === null || (is_array($app) && count($app) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $app when calling getFieldAclForGuestSpace'
            );
        }


        $resourcePath = '/k/guest/{guestSpaceId}/v1/field/acl.json';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $app,
            'app', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);


        // path params
        if ($guest_space_id !== null) {
            $resourcePath = str_replace(
                '{' . 'guestSpaceId' . '}',
                ObjectSerializer::toPathValue($guest_space_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getPreviewFieldAcl
     *
     * @param  int $app The App ID. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPreviewFieldAcl'] to see the possible values for this operation
     *
     * @throws \Kintone\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Kintone\Model\GetPreviewFieldAclResponse
     */
    public function getPreviewFieldAcl($app, string $contentType = self::contentTypes['getPreviewFieldAcl'][0])
    {
        list($response) = $this->getPreviewFieldAclWithHttpInfo($app, $contentType);
        return $response;
    }

    /**
     * Operation getPreviewFieldAclWithHttpInfo
     *
     * @param  int $app The App ID. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPreviewFieldAcl'] to see the possible values for this operation
     *
     * @throws \Kintone\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Kintone\Model\GetPreviewFieldAclResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getPreviewFieldAclWithHttpInfo($app, string $contentType = self::contentTypes['getPreviewFieldAcl'][0])
    {
        $request = $this->getPreviewFieldAclRequest($app, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Kintone\Model\GetPreviewFieldAclResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Kintone\Model\GetPreviewFieldAclResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Kintone\Model\GetPreviewFieldAclResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getPreviewFieldAclAsync
     *
     * @param  int $app The App ID. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPreviewFieldAcl'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getPreviewFieldAclAsync($app, string $contentType = self::contentTypes['getPreviewFieldAcl'][0])
    {
        return $this->getPreviewFieldAclAsyncWithHttpInfo($app, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getPreviewFieldAclAsyncWithHttpInfo
     *
     * @param  int $app The App ID. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPreviewFieldAcl'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getPreviewFieldAclAsyncWithHttpInfo($app, string $contentType = self::contentTypes['getPreviewFieldAcl'][0])
    {
        $returnType = '\Kintone\Model\GetPreviewFieldAclResponse';
        $request = $this->getPreviewFieldAclRequest($app, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getPreviewFieldAcl'
     *
     * @param  int $app The App ID. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPreviewFieldAcl'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getPreviewFieldAclRequest($app, string $contentType = self::contentTypes['getPreviewFieldAcl'][0])
    {

        // verify the required parameter 'app' is set
        if ($app === null || (is_array($app) && count($app) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $app when calling getPreviewFieldAcl'
            );
        }


        $resourcePath = '/k/v1/preview/field/acl.json';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $app,
            'app', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getPreviewFieldAclForGuestSpace
     *
     * @param  int $guest_space_id guest space id (required)
     * @param  int $app The App ID. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPreviewFieldAclForGuestSpace'] to see the possible values for this operation
     *
     * @throws \Kintone\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Kintone\Model\GetPreviewFieldAclForGuestSpaceResponse
     */
    public function getPreviewFieldAclForGuestSpace($guest_space_id, $app, string $contentType = self::contentTypes['getPreviewFieldAclForGuestSpace'][0])
    {
        list($response) = $this->getPreviewFieldAclForGuestSpaceWithHttpInfo($guest_space_id, $app, $contentType);
        return $response;
    }

    /**
     * Operation getPreviewFieldAclForGuestSpaceWithHttpInfo
     *
     * @param  int $guest_space_id guest space id (required)
     * @param  int $app The App ID. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPreviewFieldAclForGuestSpace'] to see the possible values for this operation
     *
     * @throws \Kintone\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Kintone\Model\GetPreviewFieldAclForGuestSpaceResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getPreviewFieldAclForGuestSpaceWithHttpInfo($guest_space_id, $app, string $contentType = self::contentTypes['getPreviewFieldAclForGuestSpace'][0])
    {
        $request = $this->getPreviewFieldAclForGuestSpaceRequest($guest_space_id, $app, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Kintone\Model\GetPreviewFieldAclForGuestSpaceResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Kintone\Model\GetPreviewFieldAclForGuestSpaceResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Kintone\Model\GetPreviewFieldAclForGuestSpaceResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getPreviewFieldAclForGuestSpaceAsync
     *
     * @param  int $guest_space_id guest space id (required)
     * @param  int $app The App ID. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPreviewFieldAclForGuestSpace'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getPreviewFieldAclForGuestSpaceAsync($guest_space_id, $app, string $contentType = self::contentTypes['getPreviewFieldAclForGuestSpace'][0])
    {
        return $this->getPreviewFieldAclForGuestSpaceAsyncWithHttpInfo($guest_space_id, $app, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getPreviewFieldAclForGuestSpaceAsyncWithHttpInfo
     *
     * @param  int $guest_space_id guest space id (required)
     * @param  int $app The App ID. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPreviewFieldAclForGuestSpace'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getPreviewFieldAclForGuestSpaceAsyncWithHttpInfo($guest_space_id, $app, string $contentType = self::contentTypes['getPreviewFieldAclForGuestSpace'][0])
    {
        $returnType = '\Kintone\Model\GetPreviewFieldAclForGuestSpaceResponse';
        $request = $this->getPreviewFieldAclForGuestSpaceRequest($guest_space_id, $app, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getPreviewFieldAclForGuestSpace'
     *
     * @param  int $guest_space_id guest space id (required)
     * @param  int $app The App ID. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPreviewFieldAclForGuestSpace'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getPreviewFieldAclForGuestSpaceRequest($guest_space_id, $app, string $contentType = self::contentTypes['getPreviewFieldAclForGuestSpace'][0])
    {

        // verify the required parameter 'guest_space_id' is set
        if ($guest_space_id === null || (is_array($guest_space_id) && count($guest_space_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $guest_space_id when calling getPreviewFieldAclForGuestSpace'
            );
        }

        // verify the required parameter 'app' is set
        if ($app === null || (is_array($app) && count($app) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $app when calling getPreviewFieldAclForGuestSpace'
            );
        }


        $resourcePath = '/k/guest/{guestSpaceId}/v1/preview/field/acl.json';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $app,
            'app', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);


        // path params
        if ($guest_space_id !== null) {
            $resourcePath = str_replace(
                '{' . 'guestSpaceId' . '}',
                ObjectSerializer::toPathValue($guest_space_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation putFieldAcl
     *
     * @param  \Kintone\Model\PutFieldAclRequest $put_field_acl_request put_field_acl_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['putFieldAcl'] to see the possible values for this operation
     *
     * @throws \Kintone\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Kintone\Model\PutFieldAclResponse
     */
    public function putFieldAcl($put_field_acl_request, string $contentType = self::contentTypes['putFieldAcl'][0])
    {
        list($response) = $this->putFieldAclWithHttpInfo($put_field_acl_request, $contentType);
        return $response;
    }

    /**
     * Operation putFieldAclWithHttpInfo
     *
     * @param  \Kintone\Model\PutFieldAclRequest $put_field_acl_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['putFieldAcl'] to see the possible values for this operation
     *
     * @throws \Kintone\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Kintone\Model\PutFieldAclResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function putFieldAclWithHttpInfo($put_field_acl_request, string $contentType = self::contentTypes['putFieldAcl'][0])
    {
        $request = $this->putFieldAclRequest($put_field_acl_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Kintone\Model\PutFieldAclResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Kintone\Model\PutFieldAclResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Kintone\Model\PutFieldAclResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation putFieldAclAsync
     *
     * @param  \Kintone\Model\PutFieldAclRequest $put_field_acl_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['putFieldAcl'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function putFieldAclAsync($put_field_acl_request, string $contentType = self::contentTypes['putFieldAcl'][0])
    {
        return $this->putFieldAclAsyncWithHttpInfo($put_field_acl_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation putFieldAclAsyncWithHttpInfo
     *
     * @param  \Kintone\Model\PutFieldAclRequest $put_field_acl_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['putFieldAcl'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function putFieldAclAsyncWithHttpInfo($put_field_acl_request, string $contentType = self::contentTypes['putFieldAcl'][0])
    {
        $returnType = '\Kintone\Model\PutFieldAclResponse';
        $request = $this->putFieldAclRequest($put_field_acl_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'putFieldAcl'
     *
     * @param  \Kintone\Model\PutFieldAclRequest $put_field_acl_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['putFieldAcl'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function putFieldAclRequest($put_field_acl_request, string $contentType = self::contentTypes['putFieldAcl'][0])
    {

        // verify the required parameter 'put_field_acl_request' is set
        if ($put_field_acl_request === null || (is_array($put_field_acl_request) && count($put_field_acl_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $put_field_acl_request when calling putFieldAcl'
            );
        }


        $resourcePath = '/k/v1/field/acl.json';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($put_field_acl_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($put_field_acl_request));
            } else {
                $httpBody = $put_field_acl_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation putFieldAclForGuestSpace
     *
     * @param  int $guest_space_id guest space id (required)
     * @param  \Kintone\Model\PutFieldAclForGuestSpaceRequest $put_field_acl_for_guest_space_request put_field_acl_for_guest_space_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['putFieldAclForGuestSpace'] to see the possible values for this operation
     *
     * @throws \Kintone\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Kintone\Model\PutFieldAclForGuestSpaceResponse
     */
    public function putFieldAclForGuestSpace($guest_space_id, $put_field_acl_for_guest_space_request, string $contentType = self::contentTypes['putFieldAclForGuestSpace'][0])
    {
        list($response) = $this->putFieldAclForGuestSpaceWithHttpInfo($guest_space_id, $put_field_acl_for_guest_space_request, $contentType);
        return $response;
    }

    /**
     * Operation putFieldAclForGuestSpaceWithHttpInfo
     *
     * @param  int $guest_space_id guest space id (required)
     * @param  \Kintone\Model\PutFieldAclForGuestSpaceRequest $put_field_acl_for_guest_space_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['putFieldAclForGuestSpace'] to see the possible values for this operation
     *
     * @throws \Kintone\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Kintone\Model\PutFieldAclForGuestSpaceResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function putFieldAclForGuestSpaceWithHttpInfo($guest_space_id, $put_field_acl_for_guest_space_request, string $contentType = self::contentTypes['putFieldAclForGuestSpace'][0])
    {
        $request = $this->putFieldAclForGuestSpaceRequest($guest_space_id, $put_field_acl_for_guest_space_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Kintone\Model\PutFieldAclForGuestSpaceResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Kintone\Model\PutFieldAclForGuestSpaceResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Kintone\Model\PutFieldAclForGuestSpaceResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation putFieldAclForGuestSpaceAsync
     *
     * @param  int $guest_space_id guest space id (required)
     * @param  \Kintone\Model\PutFieldAclForGuestSpaceRequest $put_field_acl_for_guest_space_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['putFieldAclForGuestSpace'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function putFieldAclForGuestSpaceAsync($guest_space_id, $put_field_acl_for_guest_space_request, string $contentType = self::contentTypes['putFieldAclForGuestSpace'][0])
    {
        return $this->putFieldAclForGuestSpaceAsyncWithHttpInfo($guest_space_id, $put_field_acl_for_guest_space_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation putFieldAclForGuestSpaceAsyncWithHttpInfo
     *
     * @param  int $guest_space_id guest space id (required)
     * @param  \Kintone\Model\PutFieldAclForGuestSpaceRequest $put_field_acl_for_guest_space_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['putFieldAclForGuestSpace'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function putFieldAclForGuestSpaceAsyncWithHttpInfo($guest_space_id, $put_field_acl_for_guest_space_request, string $contentType = self::contentTypes['putFieldAclForGuestSpace'][0])
    {
        $returnType = '\Kintone\Model\PutFieldAclForGuestSpaceResponse';
        $request = $this->putFieldAclForGuestSpaceRequest($guest_space_id, $put_field_acl_for_guest_space_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'putFieldAclForGuestSpace'
     *
     * @param  int $guest_space_id guest space id (required)
     * @param  \Kintone\Model\PutFieldAclForGuestSpaceRequest $put_field_acl_for_guest_space_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['putFieldAclForGuestSpace'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function putFieldAclForGuestSpaceRequest($guest_space_id, $put_field_acl_for_guest_space_request, string $contentType = self::contentTypes['putFieldAclForGuestSpace'][0])
    {

        // verify the required parameter 'guest_space_id' is set
        if ($guest_space_id === null || (is_array($guest_space_id) && count($guest_space_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $guest_space_id when calling putFieldAclForGuestSpace'
            );
        }

        // verify the required parameter 'put_field_acl_for_guest_space_request' is set
        if ($put_field_acl_for_guest_space_request === null || (is_array($put_field_acl_for_guest_space_request) && count($put_field_acl_for_guest_space_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $put_field_acl_for_guest_space_request when calling putFieldAclForGuestSpace'
            );
        }


        $resourcePath = '/k/guest/{guestSpaceId}/v1/field/acl.json';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($guest_space_id !== null) {
            $resourcePath = str_replace(
                '{' . 'guestSpaceId' . '}',
                ObjectSerializer::toPathValue($guest_space_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($put_field_acl_for_guest_space_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($put_field_acl_for_guest_space_request));
            } else {
                $httpBody = $put_field_acl_for_guest_space_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation putPreviewFieldAcl
     *
     * @param  \Kintone\Model\PutPreviewFieldAclRequest $put_preview_field_acl_request put_preview_field_acl_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['putPreviewFieldAcl'] to see the possible values for this operation
     *
     * @throws \Kintone\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Kintone\Model\PutPreviewFieldAclResponse
     */
    public function putPreviewFieldAcl($put_preview_field_acl_request, string $contentType = self::contentTypes['putPreviewFieldAcl'][0])
    {
        list($response) = $this->putPreviewFieldAclWithHttpInfo($put_preview_field_acl_request, $contentType);
        return $response;
    }

    /**
     * Operation putPreviewFieldAclWithHttpInfo
     *
     * @param  \Kintone\Model\PutPreviewFieldAclRequest $put_preview_field_acl_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['putPreviewFieldAcl'] to see the possible values for this operation
     *
     * @throws \Kintone\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Kintone\Model\PutPreviewFieldAclResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function putPreviewFieldAclWithHttpInfo($put_preview_field_acl_request, string $contentType = self::contentTypes['putPreviewFieldAcl'][0])
    {
        $request = $this->putPreviewFieldAclRequest($put_preview_field_acl_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Kintone\Model\PutPreviewFieldAclResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Kintone\Model\PutPreviewFieldAclResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Kintone\Model\PutPreviewFieldAclResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation putPreviewFieldAclAsync
     *
     * @param  \Kintone\Model\PutPreviewFieldAclRequest $put_preview_field_acl_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['putPreviewFieldAcl'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function putPreviewFieldAclAsync($put_preview_field_acl_request, string $contentType = self::contentTypes['putPreviewFieldAcl'][0])
    {
        return $this->putPreviewFieldAclAsyncWithHttpInfo($put_preview_field_acl_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation putPreviewFieldAclAsyncWithHttpInfo
     *
     * @param  \Kintone\Model\PutPreviewFieldAclRequest $put_preview_field_acl_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['putPreviewFieldAcl'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function putPreviewFieldAclAsyncWithHttpInfo($put_preview_field_acl_request, string $contentType = self::contentTypes['putPreviewFieldAcl'][0])
    {
        $returnType = '\Kintone\Model\PutPreviewFieldAclResponse';
        $request = $this->putPreviewFieldAclRequest($put_preview_field_acl_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'putPreviewFieldAcl'
     *
     * @param  \Kintone\Model\PutPreviewFieldAclRequest $put_preview_field_acl_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['putPreviewFieldAcl'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function putPreviewFieldAclRequest($put_preview_field_acl_request, string $contentType = self::contentTypes['putPreviewFieldAcl'][0])
    {

        // verify the required parameter 'put_preview_field_acl_request' is set
        if ($put_preview_field_acl_request === null || (is_array($put_preview_field_acl_request) && count($put_preview_field_acl_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $put_preview_field_acl_request when calling putPreviewFieldAcl'
            );
        }


        $resourcePath = '/k/v1/preview/field/acl.json';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($put_preview_field_acl_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($put_preview_field_acl_request));
            } else {
                $httpBody = $put_preview_field_acl_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation putPreviewFieldAclForGuestSpace
     *
     * @param  int $guest_space_id guest space id (required)
     * @param  \Kintone\Model\PutPreviewFieldAclForGuestSpaceRequest $put_preview_field_acl_for_guest_space_request put_preview_field_acl_for_guest_space_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['putPreviewFieldAclForGuestSpace'] to see the possible values for this operation
     *
     * @throws \Kintone\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Kintone\Model\PutPreviewFieldAclForGuestSpaceResponse
     */
    public function putPreviewFieldAclForGuestSpace($guest_space_id, $put_preview_field_acl_for_guest_space_request, string $contentType = self::contentTypes['putPreviewFieldAclForGuestSpace'][0])
    {
        list($response) = $this->putPreviewFieldAclForGuestSpaceWithHttpInfo($guest_space_id, $put_preview_field_acl_for_guest_space_request, $contentType);
        return $response;
    }

    /**
     * Operation putPreviewFieldAclForGuestSpaceWithHttpInfo
     *
     * @param  int $guest_space_id guest space id (required)
     * @param  \Kintone\Model\PutPreviewFieldAclForGuestSpaceRequest $put_preview_field_acl_for_guest_space_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['putPreviewFieldAclForGuestSpace'] to see the possible values for this operation
     *
     * @throws \Kintone\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Kintone\Model\PutPreviewFieldAclForGuestSpaceResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function putPreviewFieldAclForGuestSpaceWithHttpInfo($guest_space_id, $put_preview_field_acl_for_guest_space_request, string $contentType = self::contentTypes['putPreviewFieldAclForGuestSpace'][0])
    {
        $request = $this->putPreviewFieldAclForGuestSpaceRequest($guest_space_id, $put_preview_field_acl_for_guest_space_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Kintone\Model\PutPreviewFieldAclForGuestSpaceResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Kintone\Model\PutPreviewFieldAclForGuestSpaceResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Kintone\Model\PutPreviewFieldAclForGuestSpaceResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation putPreviewFieldAclForGuestSpaceAsync
     *
     * @param  int $guest_space_id guest space id (required)
     * @param  \Kintone\Model\PutPreviewFieldAclForGuestSpaceRequest $put_preview_field_acl_for_guest_space_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['putPreviewFieldAclForGuestSpace'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function putPreviewFieldAclForGuestSpaceAsync($guest_space_id, $put_preview_field_acl_for_guest_space_request, string $contentType = self::contentTypes['putPreviewFieldAclForGuestSpace'][0])
    {
        return $this->putPreviewFieldAclForGuestSpaceAsyncWithHttpInfo($guest_space_id, $put_preview_field_acl_for_guest_space_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation putPreviewFieldAclForGuestSpaceAsyncWithHttpInfo
     *
     * @param  int $guest_space_id guest space id (required)
     * @param  \Kintone\Model\PutPreviewFieldAclForGuestSpaceRequest $put_preview_field_acl_for_guest_space_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['putPreviewFieldAclForGuestSpace'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function putPreviewFieldAclForGuestSpaceAsyncWithHttpInfo($guest_space_id, $put_preview_field_acl_for_guest_space_request, string $contentType = self::contentTypes['putPreviewFieldAclForGuestSpace'][0])
    {
        $returnType = '\Kintone\Model\PutPreviewFieldAclForGuestSpaceResponse';
        $request = $this->putPreviewFieldAclForGuestSpaceRequest($guest_space_id, $put_preview_field_acl_for_guest_space_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'putPreviewFieldAclForGuestSpace'
     *
     * @param  int $guest_space_id guest space id (required)
     * @param  \Kintone\Model\PutPreviewFieldAclForGuestSpaceRequest $put_preview_field_acl_for_guest_space_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['putPreviewFieldAclForGuestSpace'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function putPreviewFieldAclForGuestSpaceRequest($guest_space_id, $put_preview_field_acl_for_guest_space_request, string $contentType = self::contentTypes['putPreviewFieldAclForGuestSpace'][0])
    {

        // verify the required parameter 'guest_space_id' is set
        if ($guest_space_id === null || (is_array($guest_space_id) && count($guest_space_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $guest_space_id when calling putPreviewFieldAclForGuestSpace'
            );
        }

        // verify the required parameter 'put_preview_field_acl_for_guest_space_request' is set
        if ($put_preview_field_acl_for_guest_space_request === null || (is_array($put_preview_field_acl_for_guest_space_request) && count($put_preview_field_acl_for_guest_space_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $put_preview_field_acl_for_guest_space_request when calling putPreviewFieldAclForGuestSpace'
            );
        }


        $resourcePath = '/k/guest/{guestSpaceId}/v1/preview/field/acl.json';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($guest_space_id !== null) {
            $resourcePath = str_replace(
                '{' . 'guestSpaceId' . '}',
                ObjectSerializer::toPathValue($guest_space_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($put_preview_field_acl_for_guest_space_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($put_preview_field_acl_for_guest_space_request));
            } else {
                $httpBody = $put_preview_field_acl_for_guest_space_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
